<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.0
 */

/**
 * The template for displaying Search Results pages.
 *
 * @link http://codex.wordpress.org/Template_Hierarchy
 */

get_header(); ?>

		<section id="main-content" <?php t_em_breakpoint( 'main-content' ); ?>>
			<section id="content" role="main" <?php t_em_breakpoint( 'content' ); ?>>
				<?php do_action( 't_em_action_content_before' ); ?>
				<?php
				$args = array(
					'post_type'		=> array( 'qm-export-product', 'qm-import-product' ),
					'post_status'	=> 'publish',
					'meta_query'	=> array(
						'relation'		=> 'OR',
						array(
							'key'		=> 'qm_product_description',
							'value'		=> get_search_query(),
							'compare'	=> 'LIKE',
							'type'		=> 'CHAR',
						),
						array(
							'key'		=> 'qm_product_use',
							'value'		=> get_search_query(),
							'compare'	=> 'LIKE',
							'type'		=> 'CHAR',
						),
					),
				);

				$search_query = new WP_Query( $args );

				if ( $search_query->have_posts() ) :
					while ( $search_query->have_posts() ) :
						$search_query->the_post();
						get_template_part( '/template-parts/content', 'search' );
					endwhile;
					wp_reset_postdata();
				else :
					get_template_part( '/template-parts/content', 'none' );
				endif;
				?>
				<?php do_action( 't_em_action_content_after' ); ?>
			</section><!-- #content -->
			<?php get_sidebar(); ?>
			<?php get_sidebar( 'alt' ); ?>
		</section><!-- #main-content -->

<?php get_footer(); ?>
